### ISSUE TITLE
java.lang.RuntimeException

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#1]
Comment:"при выборе знаков"

Stacktrace:
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=1, data=Intent { (has extras) }} to activity {org.fruct.oss.getssupplement/org.fruct.oss.getssupplement.AddNewPointActivity}: java.lang.NullPointerException
at android.app.ActivityThread.deliverResults(ActivityThread.java:3319)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3362)
at android.app.ActivityThread.access$1100(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1282)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5039)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
at org.fruct.oss.getssupplement.AddNewPointActivity.onActivityResult(AddNewPointActivity.java:225)
at android.app.Activity.dispatchActivityResult(Activity.java:5293)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3315)
... 11 more

**Comment by ksarkes** [comment]
fixed
