### ISSUE TITLE
  java.lang.NullPointerException  место: org.fruct.oss.getssupplement.LoginActivity$1.onPostExecute

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#14]
Версия: 2.1

Устройство: DEXP_Ursus_8EV2_3G

Комментарий: при запуске. точек нет

Стек:
java.lang.NullPointerException
    at org.fruct.oss.getssupplement.LoginActivity$1.onPostExecute(LoginActivity.java:38)
    at org.fruct.oss.getssupplement.LoginActivity$1.onPostExecute(LoginActivity.java:30)
    at android.os.AsyncTask.finish(AsyncTask.java:632)
    at android.os.AsyncTask.access$600(AsyncTask.java:177)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5292)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by seekerk** [comment]
https://github.com/oss-fruct-org/gets-supplement-android/commit/fe03a512774d4ee724193a36edbaf71fd0a4763d
