### ISSUE TITLE
  java.lang.NullPointerException  место: org.fruct.oss.getssupplement.AddNewPointActivity.onActivityResult

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#18]
Message:  
возникла ошибка при выборе категории при добавлении точки

Stacktrace:
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=3, result=1, data=Intent { (has extras) }} to activity {org.fruct.oss.getssupplement/org.fruct.oss.getssupplement.AddNewPointActivity}: java.lang.NullPointerException
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3553)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3596)
    at android.app.ActivityThread.access$1300(ActivityThread.java:151)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1369)
    at android.os.Handler.dispatchMessage(Handler.java:110)
    at android.os.Looper.loop(Looper.java:193)
    at android.app.ActivityThread.main(ActivityThread.java:5292)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.NullPointerException
    at org.fruct.oss.getssupplement.AddNewPointActivity.onActivityResult(AddNewPointActivity.java:280)
    at android.app.Activity.dispatchActivityResult(Activity.java:5456)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3549)
    ... 11 more

**Comment by seekerk** [comment]
Ошибка проявляется всегда, в т.ч. при полной очистке данных приложения

**Comment by ksarkes** [comment]
дописал проверку
