### ISSUE TITLE
java.lang.NullPointerException  место: org.fruct.oss.getssupplement.MapActivity.startFollow

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#23]
При запуске

Лог:
java.lang.NullPointerException
    at org.fruct.oss.getssupplement.MapActivity.startFollow(MapActivity.java:697)
    at org.fruct.oss.getssupplement.MapActivity.onCreateOptionsMenu(MapActivity.java:677)
    at android.app.Activity.onCreatePanelMenu(Activity.java:2646)
    at com.android.internal.policy.impl.PhoneWindow.preparePanel(PhoneWindow.java:512)
    at com.android.internal.policy.impl.PhoneWindow.doInvalidatePanelMenu(PhoneWindow.java:881)
    at com.android.internal.policy.impl.PhoneWindow$1.run(PhoneWindow.java:297)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:813)
    at android.view.Choreographer.doCallbacks(Choreographer.java:613)
    at android.view.Choreographer.doFrame(Choreographer.java:582)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:799)
    at android.os.Handler.handleCallback(Handler.java:733)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5593)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)

**Comment by temansky** [comment]
https://github.com/oss-fruct-org/gets-supplement-android/commit/e1e3aa6c34b1573a32bf41d7de1289ddc05261eb
