### ISSUE TITLE
  android.database.sqlite.SQLiteDatabaseLockedException  место: android.database.sqlite.SQLiteConnection.nativeExecuteForLong

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#26]
После недолгого использования

Стек:
java.lang.RuntimeException: Unable to start activity ComponentInfo{org.fruct.oss.getssupplement/org.fruct.oss.getssupplement.CategoryActivity}: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2412)
    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2470)
    at android.app.ActivityThread.access$900(ActivityThread.java:174)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1307)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:146)
    at android.app.ActivityThread.main(ActivityThread.java:5593)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:515)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
    at dalvik.system.NativeStart.main(Native Method)
Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5)
    at android.database.sqlite.SQLiteConnection.nativeExecuteForLong(Native Method)
    at android.database.sqlite.SQLiteConnection.executeForLong(SQLiteConnection.java:788)
    at android.database.sqlite.SQLiteSession.executeForLong(SQLiteSession.java:652)
    at android.database.sqlite.SQLiteStatement.simpleQueryForLong(SQLiteStatement.java:107)
    at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:825)
    at android.database.DatabaseUtils.longForQuery(DatabaseUtils.java:813)
    at android.database.sqlite.SQLiteDatabase.getVersion(SQLiteDatabase.java:996)
    at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:242)
    at android.database.sqlite.SQLiteOpenHelper.getReadableDatabase(SQLiteOpenHelper.java:188)
    at org.fruct.oss.getssupplement.Database.GetsDbHelper.getCategories(GetsDbHelper.java:128)
    at org.fruct.oss.getssupplement.CategoryActivity.onCreate(CategoryActivity.java:31)
    at android.app.Activity.performCreate(Activity.java:5458)
    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
    ... 11 more

**Comment by ksarkes** [comment]
https://github.com/oss-fruct-org/gets-supplement-android/commit/81db752e899b493d25cd5bf8379428bae058c4e8
