### ISSUE TITLE
android.database.sqlite.SQLiteException: Can't downgrade database from version 3 to 1

### ISSUE THREAD

**Issue by seekerk** [oss-fruct-org/gets-supplement-android#3]
Comment:
- при открытии
- при сдвиге карты выдаёт ошибку

Stacktrace:
android.database.sqlite.SQLiteException: Can't downgrade database from version 3 to 1
at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:361)
at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:255)
at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:164)
at org.fruct.oss.getssupplement.Database.GetsDbHelper.addCategory(GetsDbHelper.java:105)
at org.fruct.oss.getssupplement.Database.GetsDbHelper.addCategories(GetsDbHelper.java:121)
at org.fruct.oss.getssupplement.MapActivity$4.onPostExecute(MapActivity.java:222)
at org.fruct.oss.getssupplement.MapActivity$4.onPostExecute(MapActivity.java:215)
at android.os.AsyncTask.finish(AsyncTask.java:632)
at android.os.AsyncTask.access$600(AsyncTask.java:177)
at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
at android.os.Handler.dispatchMessage(Handler.java:110)
at android.os.Looper.loop(Looper.java:193)
at android.app.ActivityThread.main(ActivityThread.java:5292)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:824)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:640)
at dalvik.system.NativeStart.main(Native Method)

**Comment by ksarkes** [comment]
fixed
